packages:
  - '.'
  - '../Repositories/easyblocks/packages/core'
  - '../Repositories/easyblocks/packages/editor'
  - '../Repositories/easyblocks/packages/design-system'
  - '../Repositories/easyblocks/packages/utils'
